### ISSUE TITLE
Maybe a bug

### ISSUE THREAD

**Issue by pepaaran** [khufkens/handful_of_pixels#7]
https://github.com/khufkens/handfull_of_pixels/blob/f05389a6698d913ea1ca140f35856c428f9a7d5e/book/phenology_algorithms.qmd#L453

In that line, the `[1]` subset is probably messing up with the `last()` function, but you're not running that part of the function (I guess with return = "end") so it's not messing up anything.

https://github.com/khufkens/handfull_of_pixels/blob/f05389a6698d913ea1ca140f35856c428f9a7d5e/book/phenology_algorithms.qmd#L280

In this other line, the `[1]` is probably redundant. I just thought people may ask about these.

**Comment by khufkens** [comment]
Thanks will figure out what is going on. Might be a stray thing from a past implementation.
